networks:
  local-network:
    driver: bridge

# docker-compose --env-file=.env.app up -d
services:
  backend:
    # NOTE: use build or image
    # build:
    #   context: ../../${APP_NAME}-app
    #   dockerfile: Dockerfile
    image: ${IMAGE_NAMESPACE}/${APP_NAME}:latest
    # pull_policy: always
    restart: unless-stopped
    ports:
      - "${EXPOSE_SERVER_PORT:-8888}:${SERVER_PORT:-8888}"
      - "${EXPOSE_MANAGEMENT_SERVER_PORT:-9999}:${MANAGEMENT_SERVER_PORT:-9999}"
    environment:
      TZ: Asia/Shanghai
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE}
      MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE: ${MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE}
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_REDIS_HOST: ${SPRING_REDIS_HOST}
    volumes:
      - ./volumes/app/${APP_NAME}:/data
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:${MANAGEMENT_SERVER_PORT:-9999}/actuator/health" ]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - local-network