--- # log
debug: false
logging:
  file:
    path: ${LOG_HOME:/app/logs/${LOG_FILE_BASENAME:${spring.application.name}}}
  level:
    space.x9x.radp: info
    space.x9x: info
    com.zaxxer.hikari.HikariConfig: debug
--- # database
spring:
  datasource:
    url: jdbc:mysql://mysql:3306/${appName}?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai&useSSL=false
    username: ENC(VDoSzyZ7jS/lvaBnAaIc3ePEo9bh6QEb)
    password: ENC(uvgZQKBNymDMjPilZgaRHAE4LEeSW1xj)
