#set( $symbol_pound = '#' )
#set( $symbol_dollar = '$' )
#set( $symbol_escape = '\' )
--- # log
debug: false
logging:
  file:
    path: ${symbol_dollar}{LOG_HOME:/app/logs/${spring.application.name}}
--- # database
spring:
  datasource:
    username: ENC(VDoSzyZ7jS/lvaBnAaIc3ePEo9bh6QEb)
    password: ENC(uvgZQKBNymDMjPilZgaRHAE4LEeSW1xj)
