--- # log
debug: false
logging:
  file:
    path: /data/logs/${spring.application.name}
  level:
    space.x9x.radp: info
    space.x9x: info
--- # database
spring:
  datasource:
    url: jdbc:mysql://mysql.m3.develop.x9x:3306/${appName}?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai&useSSL=false
    username: ENC(VDoSzyZ7jS/lvaBnAaIc3ePEo9bh6QEb)
    password: ENC(uvgZQKBNymDMjPilZgaRHAE4LEeSW1xj)