#set( $symbol_pound = '#' )
#set( $symbol_dollar = '$' )
#set( $symbol_escape = '\' )
--- # logback
debug: false
logging:
  config: classpath:radp/logback/template/logback-spring.xml
  file:
    path: ${symbol_dollar}{LOG_HOME:./logs/${spring.application.name}}
    name: ${logging.file.path}/${symbol_dollar}{LOG_FILE_BASENAME:${symbol_dollar}{HOSTNAME:${spring.application.name}}}.log # 日志文件名，全路径
  logback:
    rollingpolicy:
      max-history: 7
      total-size-cap: 1GB
      max-file-size: 30MB
  level:
    root: info
    com.ulisesbocchio.jasyptspringboot: warn
    space.x9x.radp: info
    space.x9x: info
    com.zaxxer.hikari.HikariConfig: info
