networks:
  local-network:
    driver: bridge
    name: radp-network
    external: false
services:
  devcontainer:
    # image: mcr.microsoft.com/devcontainers/base:ubuntu-22.04
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ../..:/workspace/radp:cached
    networks:
      - local-network
    environment:
      TZ: Asia/Shanghai
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "5"
        compress: "true"
        mode: "non-blocking"
        max-buffer-size: "8m"
