networks:
  local-network:
    driver: bridge
    name: ${appName}-network
    external: false

services:
  ollama:
    image: ollama/ollama:0.5.10
    restart: unless-stopped
    ports:
      - "11434:11434"
