# see https://www.jetbrains.com/help/writerside/deploy-docs-to-gitlab-pages.html
variables:
  INSTANCE: 'Writerside/radp'
  DOCKER_VERSION: '243.22562'

stages:
  - gitlab_pages_build
  - gitlab_pages_test
  - gitlab_pages

build:
  stage: gitlab_pages_build
  image: registry.jetbrains.team/p/writerside/builder/writerside-builder:$DOCKER_VERSION
  tags:
    - k8s
  script:
    - set -e
    - export DISPLAY=:99
    - Xvfb :99 &
    - PROJECT_ID=$(echo $INSTANCE | cut -d'/' -f2 | tr '[:lower:]' '[:upper:]')
    - ARTIFACT="webHelp${PROJECT_ID}2-all.zip"
    - /opt/builder/bin/idea.sh helpbuilderinspect -source-dir . -product $INSTANCE --runner gitlab -output-dir public
    - echo "Testing existence of $ARTIFACT..."
    - ls -la public
    - test -e public/$ARTIFACT
  artifacts:
    paths:
      - public/$ARTIFACT
      - public/report.json
      - public/$ALGOLIA_ARTIFACT
    expire_in: 1 week

test:
  stage: gitlab_pages_test
  image: openjdk:18-jdk-alpine
  tags:
    - k8s
  before_script:
    - apk add curl
  script:
    - cd public
    - curl -o wrs-checker.jar -L https://packages.jetbrains.team/maven/p/writerside/maven/com/jetbrains/writerside/writerside-ci-checker/1.0/writerside-ci-checker-1.0.jar
    - java -jar wrs-checker.jar report.json $INSTANCE
  dependencies:
    - build

pages:
  stage: gitlab_pages
  image: ubuntu:latest
  tags:
    - k8s
  before_script:
    - apt-get update -y && apt-get install unzip -y

  script:
    - PROJECT_ID=$(echo $INSTANCE | cut -d'/' -f2 | tr '[:lower:]' '[:upper:]')
    - ARTIFACT="webHelp${PROJECT_ID}2-all.zip"
    - echo "Using artifact $ARTIFACT"
    - cd public
    - unzip -O UTF-8 $ARTIFACT
  dependencies:
    - build
  artifacts:
    paths:
      - public
    expire_in: 1 week