networks:
  local-network:
    driver: bridge
    name: radp-network
    external: false

# rabbitmq-plugins enable rabbitmq_management
services:
  # 管理后台 http://127.0.0.1:15672
  # 账号密码 admin/admin
  rabbitmq:
    image: rabbitmq:${RABBITMQ_VERSION}
    restart: unless-stopped
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin
    command: rabbitmq-server
    volumes:
      - ./volumes/rabbitmq/enabled_plugins:/etc/rabbitmq/enabled_plugins
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "5"
        compress: "true"
        mode: "non-blocking"
        max-buffer-size: "8m"
