--- # webmvc
server:
  port: 0
--- # actuator
management:
  server:
    port: 0
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,metrics,loggers,env
  endpoint:
    loggers:
      access: unrestricted
    health:
      show-details: always
    env:
      show-values: always
--- # hikari
spring:
  datasource:
    hikari:
      data-source-properties:
        loggerLevel: INFO
--- # database
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/${appName}?createDatabaseIfNotExist=true&useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai&useSSL=false
    username: ENC(VDoSzyZ7jS/lvaBnAaIc3ePEo9bh6QEb)
    password: ENC(uvgZQKBNymDMjPilZgaRHAE4LEeSW1xj)
--- # log
debug: false
logging:
  level:
    space.x9x.radp: debug
    space.x9x: debug
    com.zaxxer.hikari.HikariConfig: debug
#    org.springframework.boot.context.config: trace
