--- # actuator
management:
  server:
    port: @app.management.server.port@
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: health,info,prometheus,metrics
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true
      group:
        readiness:
          include: readinessState
          show-details: always
        liveness:
          include: livenessState
          show-details: always
  metrics:
    tags:
      application: ${spring.application.name}
