networks:
  local-network:
    driver: bridge
    name: ${appName}-network
    external: false

services:
  backend:
    # NOTE: use build or image
    # build:
    #   context: ../../${APP_NAME}-app
    #   dockerfile: Dockerfile
    image: ${IMAGE_NAMESPACE}/${APP_NAME}:latest
    # pull_policy: always
    restart: unless-stopped
    ports:
      - "${SERVER_PORT:-8888}"
      - "${MANAGEMENT_SERVER_PORT:-9999}"
    environment:
      TZ: Asia/Shanghai
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE}

    volumes:
      - ./volumes/app/data:/data
      - ./volumes/app/config/:/app/config/

    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:${MANAGEMENT_SERVER_PORT:-9999}/actuator/health" ]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - local-network
