#set( $symbol_pound = '#' )
#set( $symbol_dollar = '$' )
#set( $symbol_escape = '\' )
networks:
  local-network:
    driver: bridge
    name: ${appName}-network
    external: false

services:
  backend:
    image: ${symbol_dollar}{IMAGE_NAMESPACE}/${symbol_dollar}{APP_NAME}:latest
    build:
      context: ..
      dockerfile: ${appName}-app/src/main/docker/Dockerfile
      args:
        # Base images
        BASE_IMAGE: ${symbol_dollar}{BASE_IMAGE:-eclipse-temurin:8-jdk}
        RUNTIME_BASE_IMAGE: ${symbol_dollar}{RUNTIME_BASE_IMAGE:-eclipse-temurin:8-jre}

        # App configuration
        APP_NAME: ${symbol_dollar}{APP_NAME:-${appName}}
        RUNTIME_ENV: ${symbol_dollar}{RUNTIME_ENV:-local}
        SERVER_PORT: ${symbol_dollar}{SERVER_PORT:-8888}
        MANAGEMENT_SERVER_PORT: ${symbol_dollar}{MANAGEMENT_SERVER_PORT:-9999}
        SPRING_PROFILES_ACTIVE: ${symbol_dollar}{SPRING_PROFILES_ACTIVE}

        # Artifactory configuration
        ARTIFACTORY_DOMAIN: ${symbol_dollar}{ARTIFACTORY_DOMAIN}
        ARTIFACTORY_USERNAME: ${symbol_dollar}{ARTIFACTORY_USERNAME}
        ARTIFACTORY_PASSWORD: ${symbol_dollar}{ARTIFACTORY_PASSWORD}

        # Container user:group
        USER: ${symbol_dollar}{CONTAINER_USER:-tmpuser}
        GROUP: ${symbol_dollar}{CONTAINER_GROUP:-tmpgroup}
        UID: ${symbol_dollar}{CONTAINER_UID:-1001}
        GID: ${symbol_dollar}{CONTAINER_GID:-1001}

        # JVM configuration
        JVM_XMS: ${symbol_dollar}{JVM_XMS:-1g}
        JVM_XMX: ${symbol_dollar}{JVM_XMX:-1g}
        JVM_XSS: ${symbol_dollar}{JVM_XSS:-256k}
        GC_MODE: ${symbol_dollar}{GC_MODE:-G1}

        # Debug configuration
        JDWP_DEBUG: ${symbol_dollar}{JDWP_DEBUG:-N}
        JDWP_PORT: ${symbol_dollar}{JDWP_PORT:-5005}
        USE_GC_LOG: ${symbol_dollar}{USE_GC_LOG:-Y}
        USE_HEAP_DUMP: ${symbol_dollar}{USE_HEAP_DUMP:-Y}
        USE_LARGE_PAGES: ${symbol_dollar}{USE_LARGE_PAGES:-Y}

        # System Configuration
        TZ: ${symbol_dollar}{TZ:-Asia/Shanghai}
        LANG: ${symbol_dollar}{LANG:-C.UTF-8}
    restart: unless-stopped
    ports:
      - "${symbol_dollar}{EXPOSE_JDWP_PORT:-5005}:${symbol_dollar}{JDWP_PORT:-5005}"
      - "${symbol_dollar}{EXPOSE_SERVER_PORT:-8888}:${symbol_dollar}{SERVER_PORT:-8888}"
      - "${symbol_dollar}{EXPOSE_MANAGEMENT_SERVER_PORT:-9999}:${symbol_dollar}{MANAGEMENT_SERVER_PORT:-9999}"
    environment:
      TZ: ${symbol_dollar}{TZ}
      SPRING_PROFILES_ACTIVE: ${symbol_dollar}{SPRING_PROFILES_ACTIVE}

    volumes:
      - ${symbol_dollar}{LOG_VOLUME:-./volumes/logs/app}:/app/logs
      - ${symbol_dollar}{DATA_VOLUME:-./volumes/app/data}:/app/data
      - ${symbol_dollar}{EXTERNAL_CONFIG_VOLUME:-./volumes/app/config/}:/workspace/config/

    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:${symbol_dollar}{MANAGEMENT_SERVER_PORT:-9999}/actuator/health" ]
      interval: 30s
      timeout: 10s
      retries: 3

    networks:
      - local-network

    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "5"
        compress: "true"
        mode: "non-blocking"
        max-buffer-size: "8m"
