spring:
  ai:
    ollama:
      base-url: http://localhost:11434
      embedding:
        model: nomic-embed-text
        options:
          num-batch: 512
    openai:
      base-url: https://api.openai.com
      api-key: ""
      embedding:
        options:
          model: text-embedding-ada-002
      chat:
        options:
          model: gpt-4o