## 二选一

--- # 方式一: mcp sse
logging:
  level:
    io.modelcontextprotocol.spec.DefaultMcpSession: error

spring:
  ai:
    mcp:
      client:
        enabled: true
        name: ${spring.application.name}
        version: ${spring.application.version}
        # default sync
        type: sync
        # MCP 客户端请求超时时长
        request-timeout: 360s
        sse:
          connections:
            # 通过 http://mcp-server-xx:8888/sse 验证服务是否成功启动
            mcp-server-xx:
              url: http://mcp-server-xx:8888

--- # 方式二: mcp stdio
#spring:
#  ai:
#    toolcallback:
#      enabled: true
#    mcp:
#      client:
#        stdio:
#          servers-configuration: classpath:/config/mcp-servers-config.json

