networks:
  local-network:
    driver: bridge

services:
  # pg 管理工具
  pgadmin:
    image: pgadmin4:9.1.0
    restart: unless-stopped
    ports:
      - "5050:80"
    environment:
      TZ: Asia/Shanghai
      PGADMIN_DEFAULT_EMAIL: admin@qq.com
      PGADMIN_DEFAULT_PASSWORD: admin
    depends_on:
      - vector_db
    networks:
      - local-network