--- # log
debug: false
logging:
  file:
    path: ${LOG_HOME:/app/logs/${spring.application.name}}
--- # database
spring:
  datasource:
    username: ENC(VDoSzyZ7jS/lvaBnAaIc3ePEo9bh6QEb)
    password: ENC(uvgZQKBNymDMjPilZgaRHAE4LEeSW1xj)
