--- # log
debug: false
logging:
  file:
    path: ../logs/${spring.application.name}
  level:
    space.x9x.radp: debug
    space.x9x: debug
    com.zaxxer.hikari.HikariConfig: debug
    org.springframework.boot.context.config: trace
--- # webmvc
server:
  port: 7080
--- # actuator
management:
  server:
    port: 7081
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,metrics,loggers,env
  endpoint:
    loggers:
      access: unrestricted
    health:
      show-details: always
    env:
      show-values: always
--- # hikari
spring:
  datasource:
    hikari:
      data-source-properties:
        loggerLevel: INFO
--- # database
spring:
  datasource:
    username: ENC(VDoSzyZ7jS/lvaBnAaIc3ePEo9bh6QEb)
    password: ENC(uvgZQKBNymDMjPilZgaRHAE4LEeSW1xj)

