#set($dollar = '$')
#set($lbrace = '{')
#set($rbrace = '}')
networks:
  local-network:
    driver: bridge
    name: ${appName}-network
    external: false

services:
  backend:
    # NOTE: use build or image
    # build:
    #   context: ../../${dollar}${lbrace}APP_NAME${rbrace}-app
    #   dockerfile: Dockerfile
    image: ${dollar}${lbrace}IMAGE_NAMESPACE${rbrace}/${dollar}${lbrace}APP_NAME${rbrace}:latest
    # pull_policy: always
    restart: unless-stopped
    ports:
      - "${dollar}${lbrace}SERVER_PORT:-8888${rbrace}"
      - "${dollar}${lbrace}MANAGEMENT_SERVER_PORT:-9999${rbrace}"
    environment:
      TZ: Asia/Shanghai
      SPRING_PROFILES_ACTIVE: ${dollar}${lbrace}SPRING_PROFILES_ACTIVE${rbrace}

    volumes:
      - ./volumes/app/data:/data
      - ./volumes/app/config/:/app/config/

    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:${dollar}${lbrace}MANAGEMENT_SERVER_PORT:-9999${rbrace}/actuator/health" ]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - local-network
