networks:
  local-network:
    driver: bridge

# docker-compose --env-file=.env.app up -d
services:
  backend:
    # NOTE: use build or image
    # build:
    #   context: ../../${APP_NAME}-app
    #   dockerfile: Dockerfile
    image: xooooooooox/${APP_NAME}:latest
    # NOTE: 等同于 --pull always
    # pull_policy: always
    restart: unless-stopped
    ports:
      - "${EXPOSE_SERVER_PORT:-8888}:${SERVER_PORT:-8888}"
      - "${EXPOSE_MANAGEMENT_SERVER_PORT:-9999}:${MANAGEMENT_SERVER_PORT:-9999}"
    environment:
      TZ: Asia/Shanghai
    volumes:
      - ./volumes/app/${APP_NAME}:/data
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:${MANAGEMENT_SERVER_PORT:-9999}/actuator/health" ]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - local-network