networks:
  local-network:
    driver: bridge
    name: radp-network
    external: false

services:
  # RedisAdmin https://github.com/joeferner/redis-commander
  # 账密 admin/admin
  redis-commander:
    image: redis-commander:${REDIS_COMMANDER_VERSION}
    hostname: redis-commander
    restart: unless-stopped
    ports:
      - "8081:8081"
    environment:
      - REDIS_HOSTS=local:redis:6379
      - HTTP_USER=admin
      - HTTP_PASSWORD=admin
      - LANG=C.UTF-8
      - LANGUAGE=C.UTF-8
      - LC_ALL=C.UTF-8
    networks:
      - local-network
