networks:
  local-network:
    driver: bridge
    name: radp-network
    external: false

services:
  mysql:
    image: mysql:${MYSQL_VERSION}
    restart: unless-stopped
    environment:
      TZ: Asia/Shanghai
      MYSQL_ROOT_PASSWORD: 123456
    ports:
      - "3306:3306"
    volumes:
      - ./volumes/mysql/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
      - ./volumes/mysql/data:/var/lib/mysql
    command:
      --default-authentication-plugin=mysql_native_password
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_unicode_ci
    networks:
      - local-network
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      interval: 5s
      timeout: 10s
      retries: 10
      start_period: 15s
