name: "[Doc] Publish Writerside Pages"

on:
  push:
    branches:
      - main
      - feat/250102-0.8
  workflow_dispatch:

permissions:
  contents: read
  id-token: write
  pages: write

jobs:
  pages:
    uses: xooooooooox/writerside-action@main
    with:
      instance: 'Writerside/radp'
      docker_version: '243.22562'