name: "[Doc] Publish Writerside Pages"

on:
  push:
    branches:
      - main
      - feat/250102-0.8
  workflow_dispatch:

jobs:
  invoke-pages-build:
    uses: xooooooooox/writerside-action@main
    with:
      instance: 'Writerside/radp'
      docker_version: '243.22562'
      branches:
        - 'main'
        - 'feat/250102-0.8'
      paths:
        - 'Writerside/*'