name: "[Pages] Build and deploy Writerside documentation to GitHub Pages"

on:
  push:
    branches:
      - main
    paths: [ 'Writerside/**/*' ]
  workflow_dispatch:

permissions:
  contents: read
  id-token: write
  pages: write

jobs:
  pages:
    runs-on: ubuntu-latest
    steps:
      - name: xxx
        uses: xooooooooox/writerside-action@main
        with:
          instance: 'Writerside/radp'
          docker_version: '243.22562'