name: "[Pages] Build and deploy Writerside documentation to GitHub Pages"

on:
  push:
    branches:
      - main
    paths: [ 'Writerside/**/*' ]
  workflow_dispatch:

permissions:
  contents: read
  id-token: write
  pages: write

jobs:
  wrs_pages:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.pages.outputs.page_url }}
    steps:
      - name: Build and deploy to GitHub Pages
        id: pages
        uses: xooooooooox/writerside-action@main
        with:
          instance: 'Writerside/radp'
          docker_version: '243.22562'