networks:
  local-network:
    driver: bridge
    name: radp-network
    external: false

services:
  ollama:
    image: ollama/ollama:${OLLAMA_VERSION}
    restart: unless-stopped
    ports:
      - "11434:11434"
